# -*- coding: utf-8 -*-
"""deep learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0dYMPh-5AQgMcjKT6RiMEZWAaoy60mz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, f1_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

from google.colab import files
uploaded = files.upload()

df = pd.read_excel("ids_dataset.xlsx")

df.head()

X = df.drop("label", axis=1)
y = df["label"]

le = LabelEncoder()
y = le.fit_transform(y)

print("Attack Classes:")
print(le.classes_)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = Sequential()

model.add(Dense(128, activation='relu', input_shape=(41,)))
model.add(Dropout(0.3))

model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(32, activation='relu'))

model.add(Dense(len(le.classes_), activation='softmax'))

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train,
    y_train,
    epochs=100,
    validation_data=(X_test, y_test),
    batch_size=8
)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("Model Accuracy")
plt.ylabel("Accuracy")
plt.xlabel("Epoch")
plt.legend(["Train", "Validation"])
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("Model Loss")
plt.ylabel("Loss")
plt.xlabel("Epoch")
plt.legend(["Train", "Validation"])
plt.show()

y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)

unique_labels_in_test_and_pred = np.unique(np.concatenate((y_test, y_pred)))
target_names_filtered = le.inverse_transform(unique_labels_in_test_and_pred)

print(classification_report(y_test, y_pred, labels=unique_labels_in_test_and_pred, target_names=target_names_filtered))

f1 = f1_score(y_test, y_pred, average='weighted', labels=unique_labels_in_test_and_pred)
print("F1 Score:", f1)

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=le.classes_,
            yticklabels=le.classes_)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

def predict_attack(*features):

    features = np.array(features).reshape(1,-1)

    prediction = model.predict(features)

    attack = le.inverse_transform([np.argmax(prediction)])

    return attack[0]

import gradio as gr
import numpy as np

def predict_attack(input_text):

    # numbers ko split karna
    features = [float(x) for x in input_text.replace(",", " ").split()]

    # check 41 features
    if len(features) != 41:
        return "Please enter exactly 41 numbers"

    features = np.array(features).reshape(1,-1)

    prediction = model.predict(features)

    attack = le.inverse_transform([np.argmax(prediction)])

    return f"Predicted Attack Type: {attack[0]}"


interface = gr.Interface(
    fn=predict_attack,
    inputs=gr.Textbox(
        lines=2,
        placeholder="Enter 41 feature values separated by space or comma"
    ),
    outputs="text",
    title="Network Intrusion Detection System",
    description="Enter all 41 feature values in one line to detect attack type"
)

interface.launch()